<?php

/** @file */

/**
 *
 *  Implements hook_entity_view()
 * 
 */

function animal_form_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {

  if ($entity->getEntityType()->id() === 'node') {
    $build['awesome'] = [
      '#markup' => '<marquee>This is Awesome</marquee>',
      '#allowed_tags' => ['marquee'],
    ];
  }
}